[build]
publish = "public"
command = '''
hugo -b /demo/ -d public/demo && \
curl -L -s https://github.com/mraerino/hugo-preview-server/releases/download/v0.1.1.pre1/preview-lambda -o functions/preview && \
'''
functions = "functions"

  [build.environment]
  HUGO_VERSION = "0.69.0"

[[redirects]]
from = "/"
to = "https://github.com/mraerino/hugo-preview-server#readme"
force = true
